# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='d_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
