# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170718_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Diagnosed'),
        ),
    ]
